"""add experience_level in preferences table and data in skills table

Revision ID: 91b05001d496
Revises: a91c44d4a9c2
Create Date: 2026-09-07 18:13:20.380120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91b05001d496'
down_revision: Union[str, Sequence[str], None] = 'a91c44d4a9c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preferences', sa.Column('experience_level', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('preferences', 'experience_level')
    # ### end Alembic commands ###
