"""Add skills data

Revision ID: 96970c8e55d3
Revises: 91b05001d496
Create Date: 2026-09-09 22:14:08.663906

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column

# revision identifiers, used by Alembic.
revision: str = "96970c8e55d3"
down_revision: Union[str, Sequence[str], None] = "91b05001d496"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

skills_table = table("skills", column("name", sa.String))


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.bulk_insert(
        skills_table,
        [
            {"name": "python"},
            {"name": "javascript"},
            {"name": "java"},
            {"name": "cs#"},
            {"name": "cpp"},
            {"name": "ruby"},
            {"name": "php"},
            {"name": "swift"},
            {"name": "kotlin"},
            {"name": "go"},
            {"name": "rust"},
            {"name": "typescript"},
            {"name": "html"},
            {"name": "css"},
            {"name": "react"},
            {"name": "angular"},
            {"name": "vuejs"},
            {"name": "django"},
            {"name": "flask"},
            {"name": "fastapi"},
            {"name": "postgresql"},
            {"name": "mysql"},
            {"name": "mongodb"},
            {"name": "mongoose"},
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        skills_table.delete().where(
            skills_table.c.name.in_(
                [
                    "python",
                    "javascript",
                    "java",
                    "cs#",
                    "cpp",
                    "ruby",
                    "php",
                    "swift",
                    "kotlin",
                    "go",
                    "rust",
                    "typescript",
                    "html",
                    "css",
                    "react",
                    "angular",
                    "vuejs",
                    "django",
                    "flask",
                    "fastapi",
                    "postgresql",
                    "mysql",
                    "mongodb",
                    "mongoose",
                ]
            )
        )
    )
    # ### end Alembic commands ###
