"""Add skills table with relation

Revision ID: a91c44d4a9c2
Revises: 02fd82f00252
Create Date: 2026-09-06 17:37:47.107031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a91c44d4a9c2'
down_revision: Union[str, Sequence[str], None] = '02fd82f00252'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('preferences_skills',
    sa.Column('preferences_id', sa.Integer(), nullable=False),
    sa.Column('skills_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['preferences_id'], ['preferences.id'], ),
    sa.ForeignKeyConstraint(['skills_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('preferences_id', 'skills_id')
    )
    op.alter_column('preferences', 'remote_work',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('preferences', 'remote_work',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_table('preferences_skills')
    op.drop_table('skills')
    # ### end Alembic commands ###
